services:
  # nginx
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
     - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    # depends_on:
    #   - php
  # php
  app:
    build:
      dockerfile: ./php/Dockerfile 
      target: development
    volumes:
      # preserve vendor folder
      - /var/www/html/vendor
      - ./app:/var/www/html
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    # depends_on:
  # mysql
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - mysqldata:/var/lib/mysql      
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8001:80
    environment:
      MYSQL_ROOT_PASSWORD: password
    # redis
  cache:
    image: redis:latest

volumes:
  mysqldata:
  # redis:
  #   driver: local
  # mysql:
  #   driver: local